from __future__ import annotations


def component(
    name,
    *,
    aliases=None,
    package_aliases=None,
    sys_crates=None,
    high_level_crates=None,
    default_source="system",
    input_class="crafted_input",
    input_tokens=None,
    rust_entrypoints=None,
    native_symbols=None,
    maturity="seed",
    default_env_guards=None,
    default_trigger_model=None,
    notes="",
):
    return {
        "component": name,
        "aliases": aliases or [],
        "package_aliases": package_aliases or [],
        "sys_crates": sys_crates or [],
        "high_level_crates": high_level_crates or [],
        "default_source": default_source,
        "input_class": input_class,
        "input_tokens": input_tokens or [],
        "rust_entrypoints": rust_entrypoints or [],
        "native_symbols": native_symbols or [],
        "maturity": maturity,
        "default_env_guards": default_env_guards or {},
        "default_trigger_model": default_trigger_model or {},
        "notes": notes,
    }


def vuln(
    component_name,
    cve,
    *,
    version_range,
    description,
    symbols,
    trigger_conditions,
    source_patterns,
    sanitizer_patterns,
    severity="high",
    maturity="seed",
    source_status="",
    rust_sinks=None,
    native_sinks=None,
    must_flow=None,
    env_guards=None,
    trigger_model=None,
    input_predicate=None,
    references=None,
    web_summary="",
    notes="",
):
    return {
        "component": component_name,
        "cve": cve,
        "version_range": version_range,
        "description": description,
        "severity": severity,
        "maturity": maturity,
        "symbols": symbols,
        "trigger_conditions": trigger_conditions,
        "source_patterns": source_patterns,
        "sanitizer_patterns": sanitizer_patterns,
        "source_status": source_status,
        "rust_sinks": rust_sinks or [],
        "native_sinks": native_sinks or [],
        "must_flow": must_flow or [],
        "env_guards": env_guards or {},
        "trigger_model": trigger_model or {},
        "input_predicate": input_predicate or {},
        "references": references or {},
        "web_summary": web_summary,
        "notes": notes,
    }


def call_cond(cid, name, *, lang="Rust", contains=None, contains_all=True):
    cond = {"id": cid, "type": "call", "name": name, "lang": lang}
    if contains:
        cond["type"] = "call_code_contains"
        cond["contains"] = list(contains)
        cond["contains_all"] = contains_all
    return cond


def input_cond(cid, klass, *, positive_tokens=None, negative_tokens=None, strategy="assume_if_not_explicit"):
    return {
        "id": cid,
        "type": "input_class",
        "class": klass,
        "positive_tokens": list(positive_tokens or []),
        "negative_tokens": list(negative_tokens or []),
        "strategy": strategy,
    }


def api_sequence(cid, steps, *, scope="any", same_method=False):
    return {
        "id": cid,
        "type": "api_sequence",
        "steps": list(steps),
        "scope": scope,
        "same_method": same_method,
    }


def any_of(cid, conditions):
    return {"id": cid, "type": "any_of", "conditions": list(conditions)}


COMPONENTS = [
    component(
        "libxml2",
        aliases=["libxml", "xml2"],
        package_aliases=["libxml", "libxml2-sys", "libxslt", "xmlsec"],
        sys_crates=["libxml2-sys"],
        high_level_crates=["libxml", "libxslt", "xmlsec"],
        input_class="crafted_xml_or_html_input",
        input_tokens=["xml", "html", "doctype", "entity", "dtd", "xpath", "schema"],
        rust_entrypoints=["Parser::parse_string", "Parser::parse_file", "xmlReadMemory", "htmlReadMemory"],
        native_symbols=["xmlReadMemory", "xmlParseMemory", "xmlCtxtReadMemory"],
        maturity="curated",
        notes="Core XML parser family used by multiple Rust bindings.",
    ),
    component(
        "expat",
        aliases=["libexpat"],
        package_aliases=["expat", "expat-sys", "xml-rs"],
        sys_crates=["expat-sys"],
        high_level_crates=["xml-rs"],
        input_class="crafted_xml_with_external_entity",
        input_tokens=["xml", "entity", "dtd", "external", "doctype", "payload"],
        rust_entrypoints=["Parser::parse", "XML_Parser::parse"],
        native_symbols=["XML_Parse", "XML_ExternalEntityParserCreate", "XML_SetExternalEntityRefHandler"],
        maturity="curated",
        notes="Entity expansion and external entity parser paths.",
    ),
    component(
        "zlib",
        aliases=["libz"],
        package_aliases=["libz-sys", "zlib-sys", "flate2", "zlib"],
        sys_crates=["libz-sys", "zlib-sys"],
        high_level_crates=["flate2", "zlib"],
        input_class="crafted_gzip_with_large_extra_field",
        input_tokens=["gzip", "zlib", "inflate", "header", "extra", "fextra"],
        rust_entrypoints=["inflateGetHeader", "inflate", "libz_sys::inflateGetHeader", "libz_sys::inflate"],
        native_symbols=["inflateInit2_", "inflateGetHeader", "inflate"],
        maturity="curated",
        notes="Inflater state and gzip extra-field parsing.",
    ),
    component(
        "libwebp",
        aliases=["webp"],
        package_aliases=["webp", "libwebp-sys"],
        sys_crates=["libwebp-sys"],
        high_level_crates=["webp"],
        input_class="crafted_webp_lossless",
        input_tokens=["webp", "image", "lossless", "decode", "frame", "vp8l"],
        rust_entrypoints=["webp::Decoder::new", "webp::Decoder::decode", "Decoder::new", "Decoder::decode"],
        native_symbols=["WebPDecode", "VP8LDecodeImage"],
        maturity="curated",
        notes="Common Rust decode wrappers land in VP8L decoder.",
    ),
    component(
        "libgit2",
        aliases=["git2"],
        package_aliases=["git2", "libgit2-sys"],
        sys_crates=["libgit2-sys"],
        high_level_crates=["git2"],
        default_source="bundled",
        input_class="crafted_revspec",
        input_tokens=["git", "revspec", "branch", "tag", "head", "range"],
        rust_entrypoints=["Repository::revparse_single", "Repository::revparse_ext", "git2::Repository::revparse_single"],
        native_symbols=["git_revparse_single", "git_revparse_ext"],
        maturity="curated",
        notes="Repository revision parsing is a stable Rust entrypoint.",
    ),
    component(
        "sqlite",
        aliases=["sqlite3"],
        package_aliases=["rusqlite", "libsqlite3-sys", "sqlite"],
        sys_crates=["libsqlite3-sys"],
        high_level_crates=["rusqlite"],
        input_class="extremely_large_string",
        input_tokens=["sqlite", "sql", "query", "blob", "text", "string"],
        rust_entrypoints=["Connection::execute", "Statement::execute", "rusqlite::Connection::execute"],
        native_symbols=["sqlite3_bind_text64", "sqlite3_bind_blob64", "sqlite3_exec"],
        maturity="curated",
        notes="Large text/blob bind paths are the useful detection surface.",
    ),
    component(
        "pcre2",
        package_aliases=["pcre2", "pcre2-sys", "grep-pcre2"],
        sys_crates=["pcre2-sys"],
        high_level_crates=["pcre2", "grep-pcre2"],
        input_class="crafted_regex_pattern",
        input_tokens=["regex", "pattern", "jit", "match", "compile"],
        rust_entrypoints=["RegexBuilder::build", "pcre2::bytes::RegexBuilder::build", "grep_pcre2::RegexMatcherBuilder::build"],
        native_symbols=["pcre2_jit_compile_8"],
        maturity="curated",
        default_env_guards={"all": [{"type": "feature_enabled", "feature": "jit"}]},
        notes="JIT-only trigger model.",
    ),
    component(
        "openssl",
        package_aliases=["openssl", "openssl-sys", "native-tls", "tokio-openssl", "hyper-openssl"],
        sys_crates=["openssl-sys"],
        high_level_crates=["openssl", "native-tls", "tokio-openssl", "hyper-openssl"],
        input_class="crafted_x509_certificate",
        input_tokens=["openssl", "ssl", "tls", "x509", "certificate", "verify", "handshake"],
        rust_entrypoints=["SslConnector::connect", "TlsConnector::connect", "SslStream::connect"],
        native_symbols=["X509_verify_cert", "SSL_connect", "SSL_do_handshake"],
        maturity="curated",
        notes="Certificate verification and handshake paths.",
    ),
    component(
        "openh264",
        package_aliases=["openh264", "openh264-sys2"],
        sys_crates=["openh264-sys2"],
        high_level_crates=["openh264"],
        default_source="binary-only",
        input_class="crafted_h264_bitstream",
        input_tokens=["h264", "nal", "video", "packet", "annexb", "rtp"],
        rust_entrypoints=["Decoder::decode", "openh264::decoder::Decoder::decode"],
        native_symbols=["WelsDecodeBs"],
        maturity="curated",
        notes="Decoder consumes attacker-controlled video packet bytes.",
    ),
    component(
        "gdal",
        package_aliases=["gdal", "gdal-sys"],
        sys_crates=["gdal-sys"],
        high_level_crates=["gdal"],
        input_class="crafted_gdal_dataset",
        input_tokens=["gdal", "dataset", "raster", "driver", "pcidsk", "pix"],
        rust_entrypoints=["Dataset::open", "Dataset::open_ex", "RasterBand::read_as"],
        native_symbols=["GDALOpen", "GDALOpenEx", "GDALRasterIOEx"],
        maturity="curated",
        notes="Dataset open plus raster IO is the common path.",
    ),
    component(
        "libheif",
        aliases=["heif"],
        package_aliases=["libheif-rs", "libheif-sys"],
        sys_crates=["libheif-sys"],
        high_level_crates=["libheif-rs"],
        input_class="crafted_heif_or_heic_file",
        input_tokens=["heif", "heic", "image", "decode", "metadata"],
        rust_entrypoints=["HeifContext::read_from_file", "HeifContext::read_from_bytes", "ImageHandle::decode"],
        native_symbols=["heif_context_read_from_file", "heif_context_read_from_memory_without_copy", "heif_decode_image"],
        maturity="curated",
        notes="Curated against published iloc parsing issue details in upstream/NVD records.",
    ),
    component(
        "freetype",
        package_aliases=["freetype", "freetype-rs", "freetype-sys", "servo-freetype-sys"],
        sys_crates=["freetype-sys"],
        high_level_crates=["freetype-rs", "freetype"],
        input_class="crafted_font_file",
        input_tokens=["font", "glyph", "ttf", "otf", "woff", "face", "render"],
        rust_entrypoints=["Library::init", "Library::new_face", "Face::load_glyph", "Face::load_char"],
        native_symbols=["FT_New_Face", "FT_Open_Face", "FT_Load_Glyph", "FT_Render_Glyph"],
        maturity="curated",
        notes="Curated against published FreeType glyph/subglyph heap corruption details.",
    ),
    component(
        "gstreamer",
        aliases=["gst"],
        package_aliases=["gstreamer", "gstreamer-sys", "gstreamer-app", "gstreamer-video"],
        sys_crates=["gstreamer-sys"],
        high_level_crates=["gstreamer", "gstreamer-app", "gstreamer-video"],
        input_class="crafted_media_stream_or_pipeline",
        input_tokens=["gstreamer", "gst", "pipeline", "video", "stream", "rtsp", "rtp", "av1"],
        rust_entrypoints=["gst::parse::launch", "gst::ElementFactory::make", "gstreamer::parse::launch"],
        native_symbols=["gst_parse_launch", "gst_element_factory_make"],
        maturity="curated",
        notes="Curated against AV1 tile-list parsing issue details.",
    ),
    component(
        "libjpeg-turbo",
        aliases=["turbojpeg"],
        package_aliases=["turbojpeg", "turbojpeg-sys", "libjpeg-turbo"],
        sys_crates=["turbojpeg-sys"],
        high_level_crates=["turbojpeg"],
        input_class="crafted_12bit_lossless_jpeg",
        input_tokens=["jpeg", "jpg", "12-bit", "lossless", "turbojpeg", "image", "decompress"],
        rust_entrypoints=["Decompressor::read_header", "Decompressor::decompress", "turbojpeg::Decompressor::decompress"],
        native_symbols=["tjDecompressHeader3", "tjDecompress2"],
        maturity="curated",
        notes="Curated against 12-bit lossless JPEG decompression issue details.",
    ),
    component(
        "cjson",
        aliases=["cJSON"],
        package_aliases=["cjson", "cjson-sys", "libcjson-sys"],
        sys_crates=["cjson-sys", "libcjson-sys"],
        high_level_crates=["cjson"],
        input_class="crafted_deep_json",
        input_tokens=["json", "object", "array", "nest", "parse", "payload"],
        rust_entrypoints=["cjson::parse", "CJson::parse", "parse_json"],
        native_symbols=["cJSON_Parse", "cJSON_ParseWithOpts"],
        maturity="curated",
        notes="Deeply nested JSON parsing path.",
    ),
    component(
        "libpng",
        aliases=["png"],
        package_aliases=["png", "libpng-sys"],
        sys_crates=["libpng-sys"],
        high_level_crates=["png"],
        input_class="crafted_interlaced_16bit_png",
        input_tokens=["png", "interlaced", "16-bit", "simplified", "read", "finish_read"],
        rust_entrypoints=["png_image_begin_read_from_memory", "png_image_finish_read", "PngImage::finish_read"],
        native_symbols=["png_image_begin_read_from_memory", "png_image_finish_read"],
        maturity="curated",
        notes="Curated against simplified API heap overflow and related published reports.",
    ),
    component(
        "libtiff",
        aliases=["tiff"],
        package_aliases=["tiff", "libtiff-sys"],
        sys_crates=["libtiff-sys"],
        high_level_crates=["tiff"],
        input_class="crafted_tiff_file",
        input_tokens=["tiff", "ifd", "strip", "tile", "image", "decode"],
        rust_entrypoints=["Decoder::new", "Decoder::read_image", "tiff::decoder::Decoder::read_image"],
        native_symbols=["TIFFOpen", "TIFFReadEncodedStrip", "TIFFReadRGBAImageOriented"],
        maturity="curated",
        notes="Curated against libtiff image/strip decoding issue details.",
    ),
    component(
        "curl",
        aliases=["libcurl"],
        package_aliases=["curl", "curl-sys", "isahc"],
        sys_crates=["curl-sys"],
        high_level_crates=["curl", "isahc"],
        input_class="crafted_long_url_or_proxy_reply",
        input_tokens=["curl", "url", "proxy", "socks5", "http", "request", "hostname"],
        rust_entrypoints=["Easy::url", "Easy::proxy", "Easy::perform", "Transfer::perform"],
        native_symbols=["curl_easy_setopt", "curl_easy_perform"],
        maturity="curated",
        notes="Curated against SOCKS5 hostname overflow advisory details.",
    ),
    component(
        "libarchive",
        aliases=["archive"],
        package_aliases=["libarchive", "libarchive3-sys"],
        sys_crates=["libarchive3-sys"],
        high_level_crates=["libarchive"],
        input_class="crafted_archive_file",
        input_tokens=["archive", "tar", "zip", "cpio", "entry", "extract"],
        rust_entrypoints=["Archive::read_new", "Archive::open_filename", "Archive::next_header"],
        native_symbols=["archive_read_open_filename", "archive_read_next_header", "archive_read_data"],
        maturity="curated",
        notes="Curated against libarchive RAR filter overflow details.",
    ),
    component(
        "libsndfile",
        aliases=["sndfile"],
        package_aliases=["sndfile", "libsndfile-sys"],
        sys_crates=["libsndfile-sys"],
        high_level_crates=["sndfile"],
        input_class="crafted_audio_file",
        input_tokens=["audio", "wav", "aiff", "ogg", "sndfile", "sample"],
        rust_entrypoints=["SndFile::open", "SndFile::read_to_end", "OpenOptions::read_only"],
        native_symbols=["sf_open", "sf_readf_short", "sf_readf_int"],
        maturity="curated",
        notes="Curated against libsndfile file-header parsing details.",
    ),
    component(
        "harfbuzz",
        aliases=["hb"],
        package_aliases=["harfbuzz_rs", "harfbuzz-sys"],
        sys_crates=["harfbuzz-sys"],
        high_level_crates=["harfbuzz_rs"],
        input_class="crafted_font_and_text",
        input_tokens=["font", "shape", "glyph", "script", "harfbuzz", "text"],
        rust_entrypoints=["Face::from_file", "Font::new", "shape"],
        native_symbols=["hb_face_create", "hb_shape"],
        maturity="curated",
        notes="Curated against HarfBuzz shaping issue details.",
    ),
    component(
        "libssh2",
        aliases=["ssh2"],
        package_aliases=["ssh2", "libssh2-sys"],
        sys_crates=["libssh2-sys"],
        high_level_crates=["ssh2"],
        input_class="crafted_ssh_handshake",
        input_tokens=["ssh", "banner", "handshake", "packet", "channel", "sftp"],
        rust_entrypoints=["Session::handshake", "Session::userauth_password", "Sftp::open"],
        native_symbols=["libssh2_session_handshake", "libssh2_channel_process_startup"],
        maturity="curated",
        notes="Curated against libssh2 transport/handshake packet issue details.",
    ),
    component(
        "libzip",
        aliases=["zip"],
        package_aliases=["zip", "libzip-sys", "zip-rs"],
        sys_crates=["libzip-sys"],
        high_level_crates=["zip", "zip-rs"],
        input_class="crafted_zip_archive",
        input_tokens=["zip", "archive", "entry", "file", "central", "directory"],
        rust_entrypoints=["ZipArchive::new", "ZipArchive::by_index", "ZipArchive::by_name"],
        native_symbols=["zip_open", "zip_fopen_index", "zip_stat_index"],
        maturity="curated",
        notes="Curated against libzip malformed archive processing details.",
    ),
    component(
        "ffmpeg",
        aliases=["avcodec", "avformat"],
        package_aliases=["ffmpeg-next", "ffmpeg-sys-next"],
        sys_crates=["ffmpeg-sys-next"],
        high_level_crates=["ffmpeg-next"],
        input_class="crafted_tile_grid_media_stream",
        input_tokens=["ffmpeg", "tile", "grid", "group", "stream", "container", "avformat"],
        rust_entrypoints=["format::input", "format::open_input", "demuxer::read_packet"],
        native_symbols=["avformat_open_input", "av_read_frame", "avformat_find_stream_info"],
        maturity="curated",
        notes="Curated against avformat tile-grid-group parsing issue details.",
    ),
    component(
        "libvpx",
        aliases=["vpx"],
        package_aliases=["libvpx-sys", "vpx"],
        sys_crates=["libvpx-sys"],
        high_level_crates=["vpx"],
        input_class="crafted_vp8_encode_frame",
        input_tokens=["vp8", "vpx", "encode", "frame", "encoder", "image"],
        rust_entrypoints=["Encoder::new", "Encoder::encode", "Config::new"],
        native_symbols=["vpx_codec_enc_init_ver", "vpx_codec_encode"],
        maturity="curated",
        notes="Curated against VP8 encoding heap overflow details.",
    ),
    component(
        "libaom",
        aliases=["aom"],
        package_aliases=["aom-sys", "libaom"],
        sys_crates=["aom-sys"],
        high_level_crates=["libaom"],
        input_class="crafted_multithreaded_av1_encode_sequence",
        input_tokens=["av1", "aom", "encode", "resolution", "frame", "threads"],
        rust_entrypoints=["Encoder::new", "Encoder::encode", "Encoder::set_threads"],
        native_symbols=["aom_codec_enc_init_ver", "aom_codec_encode"],
        maturity="curated",
        notes="Curated against multithreaded AV1 encode resolution-change overflow details.",
    ),
    component(
        "xz",
        aliases=["liblzma", "lzma"],
        package_aliases=["xz2", "lzma-sys", "xz"],
        sys_crates=["lzma-sys"],
        high_level_crates=["xz2", "xz"],
        input_class="crafted_xz_stream",
        input_tokens=["xz", "lzma", "stream", "filter", "decoder", "archive"],
        rust_entrypoints=["XzDecoder::read_to_end", "Stream::process", "XzDecoder::new"],
        native_symbols=["lzma_stream_decoder", "lzma_code"],
        maturity="curated",
        notes="Curated against xz/liblzma backdoor supply-chain compromise details.",
    ),
    component(
        "brotli",
        package_aliases=["brotli", "brotli-sys", "brotli2"],
        sys_crates=["brotli-sys"],
        high_level_crates=["brotli", "brotli2"],
        input_class="crafted_brotli_stream",
        input_tokens=["brotli", "stream", "compressed", "decode", "window"],
        rust_entrypoints=["Decompressor::new", "Decompressor::read_to_end", "BrotliDecompress"],
        native_symbols=["BrotliDecoderDecompressStream"],
        maturity="curated",
        notes="Curated against one-shot decompression integer overflow details.",
    ),
    component(
        "libyaml",
        aliases=["yaml"],
        package_aliases=["libyaml-sys", "unsafe-libyaml", "yaml-rust"],
        sys_crates=["libyaml-sys"],
        high_level_crates=["unsafe-libyaml", "yaml-rust"],
        input_class="crafted_yaml_tag_document",
        input_tokens=["yaml", "document", "tag", "uri", "parse", "scanner"],
        rust_entrypoints=["YamlLoader::load_from_str", "Parser::load", "Parser::next"],
        native_symbols=["yaml_parser_initialize", "yaml_parser_load", "yaml_parser_scan_tag_uri"],
        maturity="curated",
        notes="Curated against LibYAML tag URI scanning overflow details.",
    ),
    component(
        "libraw",
        aliases=["raw"],
        package_aliases=["libraw", "libraw-sys"],
        sys_crates=["libraw-sys"],
        high_level_crates=["libraw"],
        input_class="crafted_camera_raw_file",
        input_tokens=["raw", "dng", "nef", "cr2", "camera", "image"],
        rust_entrypoints=["Processor::open_file", "Processor::unpack", "Processor::dcraw_process"],
        native_symbols=["libraw_open_file", "libraw_unpack", "libraw_dcraw_process"],
        maturity="curated",
        notes="Curated against LibRaw RAW decode overflow details.",
    ),
    component(
        "zstd",
        aliases=["libzstd"],
        package_aliases=["zstd", "zstd-sys", "zstd-safe"],
        sys_crates=["zstd-sys"],
        high_level_crates=["zstd"],
        input_class="crafted_zstd_frame",
        input_tokens=["zstd", "frame", "dictionary", "decompress", "compress"],
        rust_entrypoints=["Decoder::new", "Decoder::read_to_end", "Encoder::new"],
        native_symbols=["ZSTD_decompress", "ZSTD_decompressStream", "ZSTD_compressStream2"],
        maturity="curated",
        notes="Zstandard compression/decompression surface used from Rust bindings.",
    ),
    component(
        "bzip2",
        aliases=["libbz2", "bz2"],
        package_aliases=["bzip2", "bzip2-sys"],
        sys_crates=["bzip2-sys"],
        high_level_crates=["bzip2"],
        input_class="crafted_bzip2_stream",
        input_tokens=["bzip2", "bz2", "stream", "decompress", "archive"],
        rust_entrypoints=["BzDecoder::new", "BzDecoder::read_to_end", "BzEncoder::new"],
        native_symbols=["BZ2_bzDecompressInit", "BZ2_bzDecompress", "BZ2_bzBuffToBuffDecompress"],
        maturity="curated",
        notes="BZip2 stream decode surface.",
    ),
    component(
        "libuv",
        aliases=["uv"],
        package_aliases=["libuv-sys", "libuv-sys2", "uv"],
        sys_crates=["libuv-sys2", "libuv-sys"],
        high_level_crates=["uv"],
        input_class="crafted_event_loop_input",
        input_tokens=["uv", "loop", "tcp", "udp", "async", "fs"],
        rust_entrypoints=["Loop::new", "Tcp::read_start", "Udp::recv_start"],
        native_symbols=["uv_run", "uv_read_start", "uv_udp_recv_start"],
        maturity="curated",
        notes="libuv event loop and network buffer handling surface.",
    ),
    component(
        "libevent",
        aliases=["event"],
        package_aliases=["libevent-sys"],
        sys_crates=["libevent-sys"],
        high_level_crates=[],
        input_class="crafted_http_request",
        input_tokens=["event", "http", "request", "buffer", "evbuffer"],
        rust_entrypoints=["evhttp::request_new", "Buffer::add"],
        native_symbols=["evhttp_request_new", "evbuffer_add", "event_base_loop"],
        maturity="curated",
        notes="libevent HTTP and buffer processing surface.",
    ),
    component(
        "libsodium",
        aliases=["sodium"],
        package_aliases=["libsodium-sys", "libsodium-sys-stable", "sodiumoxide"],
        sys_crates=["libsodium-sys"],
        high_level_crates=["sodiumoxide"],
        input_class="crafted_crypto_message",
        input_tokens=["sodium", "nonce", "ciphertext", "secretbox", "crypto"],
        rust_entrypoints=["secretbox::open", "secretbox::seal", "crypto::box_::open"],
        native_symbols=["crypto_secretbox_open_easy", "crypto_secretbox_easy"],
        maturity="curated",
        notes="libsodium authenticated encryption surface.",
    ),
    component(
        "nghttp2",
        aliases=["libnghttp2", "http2"],
        package_aliases=["nghttp2-sys"],
        sys_crates=["nghttp2-sys"],
        high_level_crates=[],
        input_class="crafted_http2_frame",
        input_tokens=["http2", "h2", "header", "frame", "stream", "hpack"],
        rust_entrypoints=["Session::mem_recv", "Session::send"],
        native_symbols=["nghttp2_session_mem_recv", "nghttp2_session_client_new"],
        maturity="curated",
        notes="HTTP/2 frame and HPACK parsing surface.",
    ),
    component(
        "c-ares",
        aliases=["cares", "ares"],
        package_aliases=["c-ares", "c-ares-sys"],
        sys_crates=["c-ares-sys"],
        high_level_crates=["c-ares"],
        input_class="crafted_dns_reply",
        input_tokens=["dns", "reply", "packet", "resolver", "ares"],
        rust_entrypoints=["Channel::query", "Channel::get_host_by_name"],
        native_symbols=["ares_process", "ares_parse_a_reply", "ares_parse_aaaa_reply"],
        maturity="curated",
        notes="DNS reply parsing surface in c-ares.",
    ),
    component(
        "oniguruma",
        aliases=["onig"],
        package_aliases=["onig", "onig_sys"],
        sys_crates=["onig_sys"],
        high_level_crates=["onig"],
        input_class="crafted_onig_regex",
        input_tokens=["regex", "pattern", "onig", "capture", "backref"],
        rust_entrypoints=["Regex::new", "Regex::captures", "Regex::search"],
        native_symbols=["onig_new", "onig_search", "onig_match"],
        maturity="curated",
        notes="Oniguruma regex compile and match surface.",
    ),
    component(
        "libusb",
        aliases=["usb"],
        package_aliases=["libusb1-sys", "rusb"],
        sys_crates=["libusb1-sys"],
        high_level_crates=["rusb"],
        input_class="crafted_usb_descriptor",
        input_tokens=["usb", "descriptor", "device", "config", "bos"],
        rust_entrypoints=["DeviceHandle::read_control", "Device::device_descriptor"],
        native_symbols=["libusb_get_device_descriptor", "libusb_get_active_config_descriptor", "libusb_control_transfer"],
        maturity="curated",
        notes="USB descriptor and control transfer surface.",
    ),
    component(
        "openjpeg",
        aliases=["jpeg2000", "jp2"],
        package_aliases=["openjpeg-sys"],
        sys_crates=["openjpeg-sys"],
        high_level_crates=[],
        input_class="crafted_jp2_image",
        input_tokens=["jp2", "jpeg2000", "image", "tile", "stream"],
        rust_entrypoints=["Decoder::decode", "Image::from_file"],
        native_symbols=["opj_create_decompress", "opj_read_header", "opj_decode"],
        maturity="curated",
        notes="JPEG 2000 decode surface.",
    ),
    component(
        "openexr",
        aliases=["exr"],
        package_aliases=["openexr", "openexr-sys"],
        sys_crates=["openexr-sys"],
        high_level_crates=["openexr"],
        input_class="crafted_exr_image",
        input_tokens=["exr", "image", "tile", "scanline", "channel"],
        rust_entrypoints=["InputFile::new", "TiledInputFile::new"],
        native_symbols=["ImfOpenInputFile", "ImfTiledInputFileNew"],
        maturity="curated",
        notes="OpenEXR image decode surface.",
    ),
    component(
        "libavif",
        aliases=["avif"],
        package_aliases=["libavif", "libavif-sys", "avif-parse"],
        sys_crates=["libavif-sys"],
        high_level_crates=["libavif", "avif-parse"],
        input_class="crafted_avif_image",
        input_tokens=["avif", "image", "grid", "item", "decode"],
        rust_entrypoints=["Decoder::parse", "Decoder::next_image"],
        native_symbols=["avifDecoderParse", "avifDecoderNextImage"],
        maturity="curated",
        notes="AVIF parse and decode surface.",
    ),
    component(
        "yara",
        package_aliases=["yara", "yara-sys"],
        sys_crates=["yara-sys"],
        high_level_crates=["yara"],
        input_class="crafted_yara_rule_and_input",
        input_tokens=["yara", "rule", "scan", "compiler", "match"],
        rust_entrypoints=["Compiler::add_rules_str", "Rules::scan_mem"],
        native_symbols=["yr_compiler_add_string", "yr_rules_scan_mem"],
        maturity="curated",
        notes="YARA rule compilation and memory scan surface.",
    ),
    component(
        "libmagic",
        aliases=["magic", "file"],
        package_aliases=["libmagic", "magic-sys"],
        sys_crates=["magic-sys"],
        high_level_crates=["libmagic"],
        input_class="crafted_file_signature",
        input_tokens=["magic", "mime", "file", "buffer", "detect"],
        rust_entrypoints=["Cookie::buffer", "Cookie::file"],
        native_symbols=["magic_buffer", "magic_file", "magic_open"],
        maturity="curated",
        notes="libmagic file signature classification surface.",
    ),
    component(
        "wolfssl",
        aliases=["ssl", "tls"],
        package_aliases=["wolfssl", "wolfssl-sys"],
        sys_crates=["wolfssl-sys"],
        high_level_crates=["wolfssl"],
        input_class="crafted_tls_handshake",
        input_tokens=["ssl", "tls", "certificate", "handshake", "wolfssl"],
        rust_entrypoints=["Context::new", "SslStream::connect"],
        native_symbols=["wolfSSL_connect", "wolfSSL_accept", "wolfSSL_CTX_load_verify_buffer"],
        maturity="curated",
        notes="wolfSSL handshake and certificate verification surface.",
    ),
    component(
        "nettle",
        package_aliases=["nettle", "nettle-sys"],
        sys_crates=["nettle-sys"],
        high_level_crates=["nettle"],
        input_class="crafted_cipher_or_asn1_input",
        input_tokens=["nettle", "cipher", "key", "asn1", "curve"],
        rust_entrypoints=["Cipher::decrypt", "Cipher::encrypt"],
        native_symbols=["nettle_cbc_decrypt", "nettle_cbc_encrypt"],
        maturity="curated",
        notes="Nettle crypto primitive surface.",
    ),
    component(
        "krb5",
        aliases=["kerberos", "libkrb5"],
        package_aliases=["krb5-sys", "cross-krb5"],
        sys_crates=["krb5-sys"],
        high_level_crates=["cross-krb5"],
        input_class="crafted_kerberos_message",
        input_tokens=["kerberos", "krb5", "ticket", "realm", "principal", "asn1"],
        rust_entrypoints=["Krb5Context::init", "Credential::acquire"],
        native_symbols=["krb5_rd_req", "krb5_get_init_creds_password", "krb5_parse_name"],
        maturity="curated",
        notes="Kerberos ticket and principal parsing surface.",
    ),
    component(
        "ncurses",
        package_aliases=["ncurses", "pancurses"],
        sys_crates=["ncurses"],
        high_level_crates=["pancurses"],
        input_class="crafted_terminal_escape_stream",
        input_tokens=["terminal", "escape", "screen", "input", "widechar"],
        rust_entrypoints=["initscr", "wgetch", "mvaddstr"],
        native_symbols=["initscr", "wgetch", "mvaddstr"],
        maturity="curated",
        notes="ncurses terminal input and display surface.",
    ),
    component(
        "jansson",
        package_aliases=["jansson", "jansson-sys"],
        sys_crates=["jansson-sys"],
        high_level_crates=["jansson"],
        input_class="crafted_json_document",
        input_tokens=["json", "object", "array", "parser", "text"],
        rust_entrypoints=["Json::loadb", "Json::loads"],
        native_symbols=["json_loadb", "json_loads", "json_unpack"],
        maturity="curated",
        notes="Jansson JSON parse surface.",
    ),
    component(
        "giflib",
        aliases=["gif"],
        package_aliases=["gif", "gif-sys"],
        sys_crates=["gif-sys"],
        high_level_crates=["gif"],
        input_class="crafted_gif_image",
        input_tokens=["gif", "image", "frame", "palette", "lzw"],
        rust_entrypoints=["Decoder::new", "DecodeOptions::read_info"],
        native_symbols=["DGifOpen", "DGifSlurp", "DGifGetLine"],
        maturity="curated",
        notes="GIF decode surface.",
    ),
]


VULNERABILITIES = [
    vuln(
        "libxml2",
        "CVE-2024-40896",
        version_range="<2.13.0",
        description="libxml2 XXE path requiring dangerous parser flags and attacker-controlled XML.",
        symbols=["xmlReadMemory", "xmlCtxtReadMemory", "xmlParseMemory"],
        trigger_conditions=[
            "attacker-controlled XML or HTML reaches a libxml2 parser entrypoint",
            "entity expansion related flags are enabled on the parsing call",
            "network/entity restrictions such as XML_PARSE_NONET are absent",
        ],
        source_patterns=["xml_body", "payload", "request_body", "read_to_string"],
        sanitizer_patterns=["XML_PARSE_NONET", "sanitize_xml", "disable_dtd", "escape"],
        severity="critical",
        maturity="curated",
        trigger_model={
            "conditions": [
                call_cond("libxml2_parse_call", "xmlReadMemory", lang="Rust"),
                call_cond(
                    "libxml2_dangerous_flags",
                    "xmlReadMemory",
                    lang="Rust",
                    contains=["XML_PARSE_NOENT", "XML_PARSE_DTDLOAD"],
                ),
                input_cond("libxml2_xml_input", "crafted_xml_or_html_input", positive_tokens=["xml", "doctype", "entity", "payload"]),
            ],
            "mitigations": [
                call_cond("libxml2_nonet", "xmlReadMemory", lang="Rust", contains=["XML_PARSE_NONET"]),
            ],
            "param_semantics": {
                "flags": [
                    {"call": "xmlReadMemory", "arg_index": 5, "requires_all": ["XML_PARSE_DTDLOAD", "XML_PARSE_NOENT"], "forbids": ["XML_PARSE_NONET"]}
                ]
            },
        },
        must_flow=["request.body -> Parser::parse_string.arg1"],
        notes="Imported from existing libxml2 rule family and refined for database layout.",
    ),
    vuln(
        "expat",
        "CVE-2024-28757",
        version_range="<2.6.2",
        description="Entity expansion DoS in external entity parser usage.",
        symbols=["XML_Parse", "XML_ExternalEntityParserCreate"],
        trigger_conditions=[
            "untrusted XML reaches XML_Parse",
            "external entity parser creation occurs on attacker-controlled content",
            "recursive entity expansion remains enabled",
        ],
        source_patterns=["xml", "payload", "stdin", "read_to_end"],
        sanitizer_patterns=["disable_dtd", "limit_entity", "sanitize_xml"],
        severity="high",
        maturity="curated",
        rust_sinks=[{"path": "Parser::parse"}, {"path": "XML_Parser::parse"}],
        native_sinks=["XML_Parse", "XML_ExternalEntityParserCreate", "XML_SetExternalEntityRefHandler"],
        trigger_model={
            "conditions": [
                api_sequence(
                    "expat_entity_sequence",
                    [
                        {"name": "XML_SetExternalEntityRefHandler", "lang": "C"},
                        {"name": "XML_Parse", "lang": "C"},
                        {"name": "XML_ExternalEntityParserCreate", "lang": "C"},
                    ],
                    same_method=False,
                ),
                input_cond("expat_xml_input", "crafted_xml_with_external_entity", positive_tokens=["xml", "entity", "dtd", "external"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "zlib",
        "CVE-2022-37434",
        version_range="<1.2.13",
        description="Out-of-bounds write when gzip extra field handling and inflate header state align.",
        symbols=["inflateGetHeader", "inflate"],
        trigger_conditions=[
            "gzip stream parsing reaches inflateGetHeader",
            "the same stream is subsequently decompressed with inflate",
            "attacker can force a large extra field length",
        ],
        source_patterns=["gzip", "inflate", "stream", "reader"],
        sanitizer_patterns=["max_extra_len", "validate_gzip_header", "strip_extra_field"],
        severity="critical",
        maturity="curated",
        trigger_model={
            "conditions": [
                api_sequence(
                    "zlib_api_sequence",
                    [
                        {"name": "inflateInit2_", "lang": "C"},
                        {"name": "inflateGetHeader", "lang": "C"},
                        {"name": "inflate", "lang": "C"},
                    ],
                    same_method=False,
                ),
                input_cond("zlib_gzip_input", "crafted_gzip_with_large_extra_field", positive_tokens=["gzip", "header", "extra", "fextra"]),
            ],
            "mitigations": [],
            "state_rules": [
                {
                    "id": "zlib_extra_len_gt_max",
                    "lhs": {"field": "extra_len", "state": "post", "source": "symbolic", "symbolic_var": "attacker_extra_len"},
                    "op": ">",
                    "rhs": {"field": "extra_max", "state": "pre", "source": "observed"},
                    "lhs_constraints": [{"op": ">=", "value": 32}],
                }
            ],
        },
    ),
    vuln(
        "libwebp",
        "CVE-2023-4863",
        version_range="<1.3.2",
        description="Lossless WebP decode path reaching vulnerable VP8L internals.",
        symbols=["WebPDecode", "VP8LDecodeImage"],
        trigger_conditions=[
            "attacker-controlled WebP bytes are fully read into memory",
            "Rust decoder construction uses those bytes",
            "decode path enters lossless VP8L handling",
        ],
        source_patterns=["image", "webp", "read_to_end", "bytes"],
        sanitizer_patterns=["image_type_check_only", "format_whitelist", "size_limit"],
        severity="critical",
        maturity="curated",
        must_flow=["ImageInfo.path -> File::open.arg1", "File::open.bytes -> Decoder::new.arg1"],
        trigger_model={
            "conditions": [
                api_sequence(
                    "webp_decode_sequence",
                    [
                        {"name_regex": "(^|::)open$", "lang": "Rust"},
                        {"name_regex": "(^|::)read_to_end$", "lang": "Rust"},
                        {"name": "webp::Decoder::new", "lang": "Rust"},
                        {"name": "webp::Decoder::decode", "lang": "Rust"},
                    ],
                    same_method=True,
                ),
                {
                    "id": "webp_branch_guard",
                    "type": "control_code_contains",
                    "contains": ["WebP"],
                    "contains_all": True,
                },
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "libgit2",
        "CVE-2024-24577",
        version_range="<1.7.2",
        description="Revision parsing path that accepts attacker-controlled revspec expressions.",
        symbols=["git_revparse_single", "git_revparse_ext"],
        trigger_conditions=[
            "attacker-controlled revision expression reaches revparse API",
            "libgit2 parses the expression without prior canonicalization",
            "repository state allows the revspec to traverse vulnerable parser logic",
        ],
        source_patterns=["arg", "revspec", "revision", "input"],
        sanitizer_patterns=["normalize_revspec", "reject_range", "allowlist_ref"],
        maturity="curated",
        trigger_model={
            "conditions": [
                any_of(
                    "libgit2_revparse_any",
                    [
                        call_cond("revparse_single", "revparse_single", lang="Rust"),
                        call_cond("revparse_ext", "revparse_ext", lang="Rust"),
                    ],
                ),
                input_cond("libgit2_revspec_input", "crafted_revspec", positive_tokens=["revspec", "branch", "tag", "head", "range"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "sqlite",
        "CVE-2022-35737",
        version_range="<3.39.2",
        description="Large text/blob handling through sqlite bind interfaces.",
        symbols=["sqlite3_bind_text64", "sqlite3_bind_blob64", "sqlite3_exec"],
        trigger_conditions=[
            "large attacker-controlled text or blob reaches a statement bind path",
            "sqlite bind length exceeds safe internal handling assumptions",
            "statement execution consumes the oversized value",
        ],
        source_patterns=["sql", "query", "blob", "text"],
        sanitizer_patterns=["truncate", "size_check", "bind_limit"],
        maturity="curated",
        trigger_model={
            "conditions": [
                any_of(
                    "sqlite_exec_any",
                    [
                        call_cond("sqlite_execute", "execute", lang="Rust"),
                        call_cond("sqlite_execute_batch", "execute_batch", lang="Rust"),
                        call_cond("sqlite_statement_execute", "Statement::execute", lang="Rust"),
                        call_cond("sqlite_query_row", "query_row", lang="Rust"),
                        call_cond("sqlite_query_map", "query_map", lang="Rust"),
                        call_cond("sqlite_statement_query", "Statement::query", lang="Rust"),
                        call_cond("sqlite_prepare", "prepare", lang="Rust"),
                    ],
                ),
                input_cond("sqlite_large_string", "extremely_large_string", positive_tokens=["sql", "sqlite", "query", "blob", "text", "string"], strategy="solve_if_length_explicit_else_assume"),
            ],
            "mitigations": [],
            "param_semantics": {
                "len": [
                    {"call": "sqlite3_bind_text64", "arg_index": 4, "op": ">", "value": 2147483647},
                    {"call": "sqlite3_bind_blob64", "arg_index": 4, "op": ">", "value": 2147483647},
                ]
            },
        },
    ),
    vuln(
        "pcre2",
        "CVE-2022-1586",
        version_range="<10.40",
        description="JIT compile path on crafted regex patterns.",
        symbols=["pcre2_jit_compile_8"],
        trigger_conditions=[
            "PCRE2 JIT feature is enabled",
            "attacker-controlled regex pattern reaches RegexBuilder::build",
            "pattern triggers vulnerable compile path",
        ],
        source_patterns=["regex", "pattern", "rule", "expression"],
        sanitizer_patterns=["disable_jit", "pattern_allowlist", "size_limit"],
        maturity="curated",
        env_guards={"all": [{"type": "feature_enabled", "feature": "jit"}]},
        trigger_model={
            "conditions": [
                any_of(
                    "pcre2_build_any",
                    [
                        {
                            "id": "pcre2_jit_builder_flags",
                            "type": "builder_flag_chain",
                            "sink": {"name": "RegexBuilder::build", "lang": "Rust"},
                            "setters": [
                                {"name": "jit_if_available", "lang": "Rust", "contains": ["true"], "contains_all": False},
                            ],
                        },
                        call_cond("pcre2_build", "RegexBuilder::build", lang="Rust", contains=["jit_if_available", "pcre2", "RegexBuilder"], contains_all=False),
                    ],
                ),
                input_cond("pcre2_pattern_input", "crafted_regex_pattern", positive_tokens=["regex", "pattern", "jit", "pcre2"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "openssl",
        "CVE-2022-3602",
        version_range=">=3.0.0,<3.0.7",
        description="Certificate verification and handshake path for crafted X.509 inputs.",
        symbols=["X509_verify_cert", "SSL_connect", "SSL_do_handshake"],
        trigger_conditions=[
            "application performs TLS handshake using vulnerable OpenSSL versions",
            "attacker-controlled certificate chain reaches verification logic",
            "verification proceeds without pre-filtering malicious certificate content",
        ],
        source_patterns=["tls", "ssl", "certificate", "connect"],
        sanitizer_patterns=["pin_certificate", "custom_verify", "reject_invalid_san"],
        maturity="curated",
        trigger_model={
            "conditions": [
                any_of(
                    "openssl_handshake_any",
                    [
                        call_cond("ssl_connect", "SslConnector::connect", lang="Rust"),
                        call_cond("tls_connect", "TlsConnector::connect", lang="Rust"),
                        call_cond("ssl_stream_connect", "SslStream::connect", lang="Rust"),
                    ],
                ),
                input_cond("openssl_x509_input", "crafted_x509_certificate", positive_tokens=["x509", "certificate", "tls", "ssl", "verify"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "openh264",
        "CVE-2025-27091",
        version_range="<0.8.0",
        description="Decoder path for crafted H.264 bitstreams reaching OpenH264 internals.",
        symbols=["WelsDecodeBs"],
        trigger_conditions=[
            "attacker-controlled packet bytes are fed into the decoder",
            "decode path reaches WelsDecodeBs with real video payload",
            "no pre-validation rejects malformed NAL structure",
        ],
        source_patterns=["packet", "frame", "nal", "video"],
        sanitizer_patterns=["validate_nal", "drop_oversized_frame", "codec_guard"],
        maturity="curated",
        trigger_model={
            "conditions": [
                any_of(
                    "openh264_decode_any",
                    [
                        call_cond("openh264_decode", "Decoder::decode", lang="Rust", contains=["packet", "buf", "bytes"], contains_all=False),
                        call_cond("openh264_from_source", "OpenH264API::from_source", lang="Rust"),
                        call_cond("openh264_with_api_config", "Decoder::with_api_config", lang="Rust"),
                    ],
                ),
                input_cond(
                    "openh264_h264_input",
                    "crafted_h264_bitstream",
                    positive_tokens=["openh264", "h264", "nal", "annexb", "decode"],
                    negative_tokens=["gstreamer", "avdec_h264", "rtph264depay", "webrtc"],
                ),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "gdal",
        "CVE-2021-45943",
        version_range=">=3.3.0,<=3.4.0",
        description="PCIDSK-triggered dataset open/raster read path in GDAL.",
        symbols=["GDALOpen", "GDALOpenEx", "GDALRasterIOEx"],
        trigger_conditions=[
            "attacker-controlled geospatial dataset is opened",
            "driver dispatch selects a vulnerable parser path",
            "subsequent raster access consumes malicious metadata or blocks",
        ],
        source_patterns=["dataset", "raster", "driver", "path"],
        sanitizer_patterns=["driver_allowlist", "format_probe", "size_limit"],
        maturity="curated",
        trigger_model={
            "conditions": [
                any_of(
                    "gdal_open_any",
                    [
                        call_cond("dataset_open", "Dataset::open", lang="Rust"),
                        call_cond("dataset_open_ex", "Dataset::open_ex", lang="Rust"),
                    ],
                ),
                input_cond("gdal_dataset_input", "crafted_gdal_dataset", positive_tokens=["gdal", "dataset", "raster", "driver", "pcidsk"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "libheif",
        "CVE-2025-68431",
        version_range="<1.21.0",
        description="libheif iloc parsing overflow reachable through crafted HEIF/HEIC containers.",
        symbols=["heif_context_read_from_file", "heif_context_read_from_memory_without_copy", "heif_decode_image"],
        trigger_conditions=[
            "attacker-controlled HEIF or HEIC bytes reach a context read path",
            "parsing walks malformed item-location metadata such as an iloc box",
            "image decode or metadata access proceeds after container parsing accepts the malicious structure",
        ],
        source_patterns=["heif", "heic", "image", "bytes"],
        sanitizer_patterns=["format_probe", "size_limit", "metadata_validate"],
        maturity="curated",
        web_summary="NVD describes an out-of-bounds write in Header::parse_iloc when processing crafted HEIF/HEIC files.",
        trigger_model={
            "conditions": [
                any_of(
                    "libheif_read_any",
                    [
                        call_cond("heif_read_file", "HeifContext::read_from_file", lang="Rust"),
                        call_cond("heif_read_bytes", "HeifContext::read_from_bytes", lang="Rust"),
                    ],
                ),
                call_cond("heif_decode", "ImageHandle::decode", lang="Rust"),
                input_cond("libheif_input", "crafted_heif_or_heic_file", positive_tokens=["heif", "heic", "image", "decode"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "freetype",
        "CVE-2025-27363",
        version_range="<2.13.1",
        description="FreeType signed-short to unsigned-long conversion issue during crafted font glyph handling.",
        symbols=["FT_New_Face", "FT_Open_Face", "FT_Load_Glyph", "FT_Render_Glyph"],
        trigger_conditions=[
            "attacker-controlled font file is opened by FreeType",
            "glyph loading or rendering processes a malicious subglyph or related glyph structure",
            "the vulnerable signed-short to unsigned-long conversion and subsequent heap write are reached",
        ],
        source_patterns=["font", "glyph", "face", "ttf"],
        sanitizer_patterns=["font_allowlist", "table_validate", "size_limit"],
        maturity="curated",
        web_summary="NVD describes an out-of-bounds write caused by assigning a signed short to an unsigned long and then writing past the heap buffer end while handling crafted font data.",
        trigger_model={
            "conditions": [
                call_cond("freetype_init", "Library::init", lang="Rust"),
                any_of(
                    "freetype_open_face_any",
                    [
                        call_cond("new_face", "Library::new_face", lang="Rust"),
                        call_cond("ft_new_face", "FT_New_Face", lang="C"),
                    ],
                ),
                any_of(
                    "freetype_render_any",
                    [
                        call_cond("load_glyph", "Face::load_glyph", lang="Rust"),
                        call_cond("load_char", "Face::load_char", lang="Rust"),
                    ],
                ),
                input_cond("freetype_font_input", "crafted_font_file", positive_tokens=["font", "glyph", "ttf", "otf", "woff"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "gstreamer",
        "CVE-2024-0444",
        version_range="<1.22.9",
        description="AV1 tile-list parsing issue in GStreamer reachable from crafted AV1 media streams.",
        symbols=["gst_parse_launch", "gst_element_factory_make"],
        trigger_conditions=[
            "attacker-controlled AV1 media reaches a GStreamer parsing or decoding pipeline",
            "the AV1 parser processes a crafted tile-list OBU",
            "tile-list metadata triggers the out-of-bounds read condition before the stream is rejected",
        ],
        source_patterns=["pipeline", "stream", "rtsp", "video", "av1", "tile", "obu"],
        sanitizer_patterns=["element_allowlist", "pipeline_validate", "disable_unsafe_plugin", "av1_sanitize"],
        maturity="curated",
        input_predicate={
            "class": "crafted_av1_tile_list_stream",
            "positive_tokens": ["av1", "tile", "list", "obu", "stream", "video"],
            "negative_tokens": [],
            "strategy": "assume_if_not_explicit",
        },
        web_summary="NVD states the AV1 codec parser may perform an out-of-bounds read when processing particular tile-list OBUs.",
        trigger_model={
            "conditions": [
                any_of(
                    "gst_launch_any",
                    [
                        call_cond("gst_parse_launch", "gst::parse::launch", lang="Rust"),
                        call_cond("gst_make", "gst::ElementFactory::make", lang="Rust"),
                    ],
                ),
                input_cond("gst_media_input", "crafted_av1_tile_list_stream", positive_tokens=["gst", "pipeline", "video", "stream", "av1", "tile", "obu"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "libjpeg-turbo",
        "CVE-2023-2804",
        version_range="<2.1.5.1",
        description="libjpeg-turbo 12-bit lossless JPEG decompression issue for crafted images with out-of-range samples.",
        symbols=["tjDecompressHeader3", "tjDecompress2"],
        trigger_conditions=[
            "attacker-controlled JPEG bytes are handed to the turbojpeg decompressor",
            "the image is a 12-bit precision lossy or lossless JPEG and decompression proceeds",
            "decompression uses merged upsampling or otherwise reaches the vulnerable 12-bit sample handling path",
        ],
        source_patterns=["jpeg", "jpg", "image", "bytes", "12-bit", "lossless"],
        sanitizer_patterns=["size_limit", "header_validate", "decode_guard", "reject_12bit_lossless"],
        maturity="curated",
        input_predicate={
            "class": "crafted_12bit_lossless_jpeg",
            "positive_tokens": ["jpeg", "12-bit", "lossless", "decompress", "image"],
            "negative_tokens": [],
            "strategy": "assume_if_not_explicit",
        },
        web_summary="NVD describes the issue as triggered by 12-bit precision lossy or lossless JPEG images with out-of-range samples during decompression, often with merged upsampling.",
        trigger_model={
            "conditions": [
                any_of(
                    "jpeg_header_any",
                    [
                        call_cond("read_header", "Decompressor::read_header", lang="Rust"),
                        call_cond("decompress", "Decompressor::decompress", lang="Rust"),
                        call_cond("decompress_image", "decompress_image", lang="Rust"),
                    ],
                ),
                input_cond("jpeg_input", "crafted_12bit_lossless_jpeg", positive_tokens=["jpeg", "jpg", "turbojpeg", "12-bit", "lossless", "image", "decompress"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "cjson",
        "CVE-2023-34153",
        version_range="<1.7.16",
        description="Deep JSON nesting or crafted structure reaching cJSON parse recursion.",
        symbols=["cJSON_Parse", "cJSON_ParseWithOpts"],
        trigger_conditions=[
            "attacker-controlled JSON string reaches cJSON_Parse",
            "parser accepts a deeply nested or adversarial object tree",
            "no pre-parse depth or size limit is applied",
        ],
        source_patterns=["json", "payload", "body", "parse"],
        sanitizer_patterns=["depth_limit", "json_schema", "input_limit"],
        maturity="curated",
        trigger_model={
            "conditions": [
                any_of(
                    "cjson_parse_any",
                    [
                        call_cond("cjson_parse", "cjson::parse", lang="Rust"),
                        call_cond("cjson_parse_with_opts", "cJSON_ParseWithOpts", lang="C"),
                    ],
                ),
                input_cond("cjson_input", "crafted_deep_json", positive_tokens=["json", "object", "array", "nest", "payload"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "libpng",
        "CVE-2025-65018",
        version_range="<1.6.50",
        description="libpng simplified API heap overflow on crafted interlaced 16-bit PNG input.",
        symbols=["png_image_begin_read_from_memory", "png_image_finish_read"],
        trigger_conditions=[
            "attacker-controlled PNG bytes reach the simplified API read path",
            "the image is interlaced 16-bit and decoding targets an 8-bit output format",
            "png_image_finish_read processes the crafted image without rejecting the bit-depth/output mismatch early",
        ],
        source_patterns=["png", "image", "interlaced", "16-bit", "finish_read"],
        sanitizer_patterns=["png_set_user_limits", "dimension_check", "reject_16bit", "output_format_check"],
        maturity="curated",
        input_predicate={
            "class": "crafted_interlaced_16bit_png",
            "positive_tokens": ["png", "interlaced", "16-bit", "finish_read", "simplified"],
            "negative_tokens": [],
            "strategy": "assume_if_not_explicit",
        },
        web_summary="NVD states libpng can overflow the heap when the simplified API reads an interlaced 16-bit PNG into an 8-bit output format.",
        trigger_model={
            "conditions": [
                any_of(
                    "libpng_simplified_api_any",
                    [
                        call_cond("begin_read", "png_image_begin_read_from_memory", lang="Rust"),
                        call_cond("finish_read", "png_image_finish_read", lang="Rust"),
                    ],
                ),
                input_cond("libpng_input", "crafted_interlaced_16bit_png", positive_tokens=["png", "interlaced", "16-bit", "image", "finish_read"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "libtiff",
        "CVE-2023-52356",
        version_range="<4.6.0",
        description="libtiff heap overflow via crafted TIFF data reaching TIFFReadRGBATileExt.",
        symbols=["TIFFOpen", "TIFFReadRGBATileExt", "TIFFReadEncodedStrip"],
        trigger_conditions=[
            "attacker-controlled TIFF file reaches a tile-reading path",
            "the application calls TIFFReadRGBATileExt or an equivalent Rust wrapper",
            "malformed TIFF tile metadata survives initial validation and triggers the heap overflow",
        ],
        source_patterns=["tiff", "image", "tile", "rgba", "read"],
        sanitizer_patterns=["ifd_validate", "strip_limit", "tile_limit"],
        maturity="curated",
        web_summary="NVD says a crafted TIFF file can trigger a heap-buffer overflow when passed to TIFFReadRGBATileExt().",
        trigger_model={
            "conditions": [
                any_of(
                    "libtiff_decode_any",
                    [
                        call_cond("tiff_decoder_new", "Decoder::new", lang="Rust"),
                        call_cond("tiff_read_image", "Decoder::read_image", lang="Rust"),
                        call_cond("tiff_read_rgba_tile", "TIFFReadRGBATileExt", lang="C"),
                    ],
                ),
                input_cond("libtiff_input", "crafted_tiff_file", positive_tokens=["tiff", "tile", "rgba", "image", "read"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "curl",
        "CVE-2023-38545",
        version_range=">=7.69.0,<8.4.0",
        description="SOCKS5 proxy and long hostname handling in libcurl request path.",
        symbols=["curl_easy_setopt", "curl_easy_perform"],
        trigger_conditions=[
            "application configures a SOCKS5 proxy path",
            "attacker controls a long hostname or redirect target",
            "request proceeds through easy_perform without hostname truncation guard",
        ],
        source_patterns=["url", "proxy", "hostname", "request"],
        sanitizer_patterns=["max_host_len", "disable_proxy", "validate_url"],
        maturity="curated",
        web_summary="NVD describes a heap overflow in the SOCKS5 proxy handshake when the hostname exceeds 255 bytes and local versus remote resolve state goes wrong.",
        trigger_model={
            "conditions": [
                call_cond("curl_easy_perform", "Easy::perform", lang="Rust"),
                call_cond("curl_proxy", "Easy::proxy", lang="Rust"),
                input_cond("curl_host_input", "crafted_long_url_or_proxy_reply", positive_tokens=["url", "proxy", "socks5", "hostname"]),
            ],
            "mitigations": [],
            "param_semantics": {
                "len": [{"call": "curl_easy_setopt", "arg_index": 2, "op": ">", "value": 255}]
            },
        },
        must_flow=["user_input.url -> Easy::url.arg1"],
    ),
    vuln(
        "libarchive",
        "CVE-2024-48957",
        version_range="<3.7.7",
        description="libarchive RAR filter processing overflow reachable from crafted RAR archives.",
        symbols=["archive_read_open_filename", "archive_read_next_header", "archive_read_data"],
        trigger_conditions=[
            "attacker-controlled RAR archive reaches libarchive open and header iteration paths",
            "RAR filter processing, including execute_filter_audio, is invoked during extraction or data read",
            "crafted filter state causes source pointers to move beyond destination bounds and triggers the heap overflow",
        ],
        source_patterns=["archive", "entry", "extract", "rar", "filter", "audio"],
        sanitizer_patterns=["entry_name_check", "size_limit", "path_traversal_guard", "disable_rar_filter"],
        maturity="curated",
        input_predicate={
            "class": "crafted_rar_archive",
            "positive_tokens": ["rar", "archive", "filter", "audio", "entry"],
            "negative_tokens": [],
            "strategy": "assume_if_not_explicit",
        },
        web_summary="NVD describes a heap-buffer overflow in libarchive's execute_filter_audio path because crafted RAR filter state lets src advance past dst.",
        trigger_model={
            "conditions": [
                api_sequence(
                    "libarchive_read_sequence",
                    [
                        {"name": "archive_read_open_filename", "lang": "C"},
                        {"name": "archive_read_next_header", "lang": "C"},
                        {"name": "archive_read_data", "lang": "C"},
                    ],
                    same_method=False,
                ),
                input_cond("libarchive_input", "crafted_rar_archive", positive_tokens=["rar", "archive", "filter", "audio", "entry"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "libsndfile",
        "CVE-2021-3246",
        version_range="<1.0.31",
        description="Audio file parse path for crafted sample containers.",
        symbols=["sf_open", "sf_readf_short", "sf_readf_int"],
        trigger_conditions=[
            "attacker-controlled audio file reaches libsndfile open or read paths",
            "the file is parsed as an AU header or another path that reaches header_read",
            "malformed header values trigger the heap buffer overflow before the file is rejected",
        ],
        source_patterns=["audio", "au", "wav", "ogg", "sample", "header"],
        sanitizer_patterns=["format_probe", "sample_limit", "header_validate", "au_header_check"],
        maturity="curated",
        web_summary="NVD attributes CVE-2021-3246 to a heap-buffer-overflow in header_read in au.c triggered by crafted audio files.",
        trigger_model={
            "conditions": [
                any_of(
                    "libsndfile_open_any",
                    [
                        call_cond("sndfile_open", "SndFile::open", lang="Rust"),
                        call_cond("sndfile_read_only", "OpenOptions::read_only", lang="Rust"),
                    ],
                ),
                input_cond("libsndfile_input", "crafted_audio_file", positive_tokens=["audio", "wav", "aiff", "ogg", "sample"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "harfbuzz",
        "CVE-2023-25193",
        version_range="<7.1.0",
        description="Font shaping path with crafted font tables and attacker-controlled text.",
        symbols=["hb_face_create", "hb_shape"],
        trigger_conditions=[
            "attacker controls the font face or font bytes used for shaping",
            "the application performs shaping on that face and text",
            "malformed OpenType layout data reaches the vulnerable lookup/shaping accelerator path",
        ],
        source_patterns=["font", "text", "glyph", "shape"],
        sanitizer_patterns=["font_sanitize", "table_validate", "shape_guard"],
        maturity="curated",
        web_summary="NVD reports an out-of-bounds write in HarfBuzz before 7.1.0 during shaping of crafted fonts.",
        trigger_model={
            "conditions": [
                call_cond("hb_face_from_file", "Face::from_file", lang="Rust"),
                call_cond("hb_shape", "shape", lang="Rust"),
                input_cond("harfbuzz_font_input", "crafted_font_and_text", positive_tokens=["font", "glyph", "shape", "text"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "libssh2",
        "CVE-2019-17498",
        version_range="<1.9.1",
        description="SSH handshake path on crafted server banner or packet sequences.",
        symbols=["libssh2_session_handshake", "libssh2_channel_process_startup"],
        trigger_conditions=[
            "client performs an SSH transport or handshake exchange with an attacker-controlled peer",
            "the peer sends an oversized or malformed SSH packet during transport handling",
            "packet-length processing reaches the vulnerable allocation/write path before disconnect",
        ],
        source_patterns=["ssh", "banner", "packet", "handshake"],
        sanitizer_patterns=["banner_length_check", "handshake_timeout", "packet_validate"],
        maturity="curated",
        web_summary="NVD describes a zero-byte allocation and out-of-bounds write in libssh2 when handling a too-long SSH packet length.",
        trigger_model={
            "conditions": [
                call_cond("libssh2_handshake", "Session::handshake", lang="Rust"),
                input_cond("libssh2_ssh_input", "crafted_ssh_handshake", positive_tokens=["ssh", "banner", "packet", "handshake"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "libzip",
        "CVE-2019-17582",
        version_range="<=1.5.1",
        description="libzip heap overflow when malformed ZIP EOCD/CD record counts diverge.",
        symbols=["zip_open", "zip_fopen_index", "zip_stat_index"],
        trigger_conditions=[
            "attacker-controlled ZIP archive is opened",
            "the end-of-central-directory record count is larger than the central-directory record count",
            "archive open or entry access proceeds far enough to trust the malformed record counts and trigger the heap overflow",
        ],
        source_patterns=["zip", "archive", "entry", "directory", "eocd"],
        sanitizer_patterns=["entry_count_limit", "name_validate", "archive_probe", "central_directory_check"],
        maturity="curated",
        web_summary="NVD states a malformed file-count field in the ZIP end-of-central-directory record can exceed the central-directory count and induce a heap overflow.",
        trigger_model={
            "conditions": [
                call_cond("zip_archive_new", "ZipArchive::new", lang="Rust"),
                any_of(
                    "zip_entry_any",
                    [
                        call_cond("zip_by_index", "ZipArchive::by_index", lang="Rust"),
                        call_cond("zip_by_name", "ZipArchive::by_name", lang="Rust"),
                    ],
                ),
                input_cond("zip_archive_input", "crafted_zip_archive", positive_tokens=["zip", "archive", "entry", "directory"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "ffmpeg",
        "CVE-2025-22920",
        version_range="<7.1.1",
        description="FFmpeg avformat issue while processing crafted tile-grid-group media streams.",
        symbols=["avformat_open_input", "av_read_frame", "avformat_find_stream_info"],
        trigger_conditions=[
            "attacker-controlled media input reaches avformat open and stream-info parsing",
            "the container or stream carries crafted tile-grid-group data",
            "avformat continues processing that tile-grid-group structure and reaches the vulnerable parser path",
        ],
        source_patterns=["stream", "packet", "frame", "tile", "grid", "group", "container"],
        sanitizer_patterns=["codec_allowlist", "probe_limit", "packet_validate", "demuxer_allowlist"],
        maturity="curated",
        input_predicate={
            "class": "crafted_tile_grid_media_stream",
            "positive_tokens": ["tile", "grid", "group", "stream", "container", "avformat"],
            "negative_tokens": [],
            "strategy": "assume_if_not_explicit",
        },
        web_summary="NVD says FFmpeg is vulnerable while processing a tile-grid-group stream in avformat before 7.1.1.",
        trigger_model={
            "conditions": [
                any_of(
                    "ffmpeg_open_any",
                    [
                        call_cond("ffmpeg_input", "format::input", lang="Rust"),
                        call_cond("ffmpeg_open_input", "format::open_input", lang="Rust"),
                    ],
                ),
                input_cond("ffmpeg_media_input", "crafted_tile_grid_media_stream", positive_tokens=["tile", "grid", "group", "stream", "container", "avformat"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "libvpx",
        "CVE-2023-5217",
        version_range="<1.13.1",
        description="libvpx VP8 encoding heap overflow on crafted frame inputs.",
        symbols=["vpx_codec_enc_init_ver", "vpx_codec_encode"],
        trigger_conditions=[
            "an application initializes a VP8 encoder using vulnerable libvpx versions",
            "attacker-controlled or externally influenced frame data is passed into the encode path",
            "encoding reaches the vulnerable VP8 path and triggers the heap overflow",
        ],
        source_patterns=["vp8", "encode", "frame", "image", "encoder"],
        sanitizer_patterns=["frame_limit", "dimension_check", "codec_guard"],
        maturity="curated",
        input_predicate={
            "class": "crafted_vp8_encode_frame",
            "positive_tokens": ["vp8", "encode", "frame", "encoder", "image"],
            "negative_tokens": [],
            "strategy": "assume_if_not_explicit",
        },
        web_summary="NVD describes CVE-2023-5217 as a heap buffer overflow in libvpx VP8 encoding before 1.13.1.",
        trigger_model={
            "conditions": [
                call_cond("libvpx_encoder_new", "Encoder::new", lang="Rust"),
                any_of(
                    "libvpx_encode_any",
                    [
                        call_cond("libvpx_encode", "Encoder::encode", lang="Rust"),
                        call_cond("libvpx_codec_encode", "vpx_codec_encode", lang="C"),
                    ],
                ),
                input_cond("libvpx_stream_input", "crafted_vp8_encode_frame", positive_tokens=["vp8", "encode", "frame", "encoder", "image"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "libaom",
        "CVE-2023-6879",
        version_range="<3.7.1",
        description="libaom multithreaded AV1 encode overflow on resolution changes between frames.",
        symbols=["aom_codec_enc_init_ver", "aom_codec_encode"],
        trigger_conditions=[
            "an application uses the AV1 encoder in multithreaded mode",
            "successive frames increase resolution in a way that reaches the vulnerable deallocation path",
            "encoding continues across that resolution change and triggers the heap overflow",
        ],
        source_patterns=["av1", "encode", "frame", "resolution", "thread"],
        sanitizer_patterns=["single_thread", "resolution_lock", "frame_dimension_check"],
        maturity="curated",
        input_predicate={
            "class": "crafted_multithreaded_av1_encode_sequence",
            "positive_tokens": ["av1", "encode", "resolution", "frame", "thread"],
            "negative_tokens": [],
            "strategy": "assume_if_not_explicit",
        },
        web_summary="NVD reports a heap buffer overflow in libaom before 3.7.1 in the AV1 encoder when processing a larger size than the previous frame in multithreaded mode.",
        trigger_model={
            "conditions": [
                any_of(
                    "libaom_encode_any",
                    [
                        call_cond("libaom_encoder_new", "Encoder::new", lang="Rust"),
                        call_cond("libaom_encode", "Encoder::encode", lang="Rust"),
                    ],
                ),
                input_cond("libaom_stream_input", "crafted_multithreaded_av1_encode_sequence", positive_tokens=["av1", "encode", "resolution", "frame", "thread"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "xz",
        "CVE-2024-3094",
        version_range=">=5.6.0,<5.6.2",
        description="LZMA/XZ decoder path under compromised library versions.",
        symbols=["lzma_stream_decoder", "lzma_code"],
        trigger_conditions=[
            "application links a compromised xz/liblzma version from the affected release window",
            "the compromised library is loaded in a context that reaches liblzma decode or related runtime entrypoints",
            "the build/runtime environment preserves the malicious supply-chain modifications rather than a clean rebuilt library",
        ],
        source_patterns=["xz", "lzma", "stream", "archive", "system", "decode"],
        sanitizer_patterns=["version_pin", "disable_system_xz", "hash_verify", "rebuild_from_clean_source"],
        severity="critical",
        maturity="curated",
        input_predicate={},
        web_summary="NVD describes CVE-2024-3094 as the xz/liblzma backdoor affecting versions 5.6.0 and 5.6.1 rather than a malformed-input parser bug.",
        trigger_model={
            "conditions": [
                any_of(
                    "xz_decoder_any",
                    [
                        call_cond("xz_new", "XzDecoder::new", lang="Rust"),
                        call_cond("xz_read_all", "XzDecoder::read_to_end", lang="Rust"),
                    ],
                ),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "brotli",
        "CVE-2020-8927",
        version_range="<=1.0.7",
        description="Brotli one-shot decompression integer overflow on very large inputs.",
        symbols=["BrotliDecoderDecompressStream"],
        trigger_conditions=[
            "attacker-controlled compressed data reaches a Brotli decompression path",
            "the one-shot decompression API or equivalent length computation receives an oversized input length greater than 2 GiB",
            "integer overflow occurs before the library rejects the payload",
        ],
        source_patterns=["brotli", "stream", "compressed", "decode", "length", "buffer"],
        sanitizer_patterns=["window_limit", "decompress_limit", "stream_validate", "max_input_len"],
        maturity="curated",
        web_summary="NVD says the Brotli decoder can overflow an integer in the one-shot decompression API with quality 11 data if the input size is larger than 2 GiB.",
        trigger_model={
            "conditions": [
                any_of(
                    "brotli_decompress_any",
                    [
                        call_cond("brotli_new", "Decompressor::new", lang="Rust"),
                        call_cond("brotli_read", "Decompressor::read_to_end", lang="Rust"),
                    ],
                ),
                input_cond("brotli_stream_input", "crafted_brotli_stream", positive_tokens=["brotli", "stream", "decode", "window"]),
            ],
            "mitigations": [],
            "param_semantics": {
                "len": [{"call": "BrotliDecoderDecompressStream", "arg_index": 2, "op": ">", "value": 2147483648}]
            },
        },
    ),
    vuln(
        "libyaml",
        "CVE-2013-6393",
        version_range="<0.1.5",
        description="LibYAML heap overflow while scanning crafted tag URIs.",
        symbols=["yaml_parser_initialize", "yaml_parser_load", "yaml_parser_scan_tag_uri"],
        trigger_conditions=[
            "attacker-controlled YAML reaches a parser load path",
            "the document contains a malicious tag URI or tag token sequence",
            "tag scanning reaches yaml_parser_scan_tag_uri and overflows before the parser rejects the input",
        ],
        source_patterns=["yaml", "document", "tag", "uri", "scanner"],
        sanitizer_patterns=["alias_limit", "depth_limit", "tag_allowlist", "tag_uri_validate"],
        maturity="curated",
        input_predicate={
            "class": "crafted_yaml_tag_document",
            "positive_tokens": ["yaml", "tag", "uri", "document", "parse"],
            "negative_tokens": [],
            "strategy": "assume_if_not_explicit",
        },
        web_summary="NVD describes a heap-based buffer overflow in yaml_parser_scan_tag_uri in LibYAML before 0.1.5.",
        trigger_model={
            "conditions": [
                any_of(
                    "yaml_load_any",
                    [
                        call_cond("yaml_load_str", "YamlLoader::load_from_str", lang="Rust"),
                        call_cond("yaml_parser_load", "Parser::load", lang="Rust"),
                    ],
                ),
                input_cond("yaml_document_input", "crafted_yaml_tag_document", positive_tokens=["yaml", "tag", "uri", "document", "parse"]),
            ],
            "mitigations": [],
        },
    ),
    vuln(
        "libraw",
        "CVE-2023-1729",
        version_range="<0.21.2",
        description="LibRaw heap-buffer-overflow in raw2image_ex reachable from crafted RAW files.",
        symbols=["libraw_open_file", "libraw_unpack", "raw2image_ex", "libraw_dcraw_process"],
        trigger_conditions=[
            "attacker-controlled camera RAW file reaches LibRaw open/unpack paths",
            "thumbnail or image unpack processing reaches raw2image_ex",
            "crafted RAW metadata triggers the heap-buffer-overflow before the image is rejected",
        ],
        source_patterns=["raw", "dng", "nef", "image"],
        sanitizer_patterns=["format_probe", "metadata_validate", "size_limit"],
        maturity="curated",
        web_summary="NVD describes a heap-buffer-overflow in LibRaw raw2image_ex() caused by a maliciously crafted RAW file.",
        trigger_model={
            "conditions": [
                api_sequence(
                    "libraw_process_sequence",
                    [
                        {"name": "libraw_open_file", "lang": "C"},
                        {"name": "libraw_unpack", "lang": "C"},
                        {"name": "raw2image_ex", "lang": "C"},
                    ],
                    same_method=False,
                ),
                input_cond("libraw_image_input", "crafted_camera_raw_file", positive_tokens=["raw", "dng", "nef", "cr2", "camera"]),
            ],
            "mitigations": [],
        },
    ),
]
